spring:
  application:
    name: springConsulApp
  cloud:
    consul:
      host: http://localhost:8500
      discovery:
        healthCheckPath: /my-health-check
        healthCheckInterval: 20s
        enabled: true
        instanceId: ${spring.application.name}:${random.value}
